
package eu.openmos.agentcloud.ws.systemconfigurator.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import eu.openmos.agentcloud.utilities.ServiceCallStatus;
import eu.openmos.model.Order;
import eu.openmos.model.Recipe;
import eu.openmos.model.Skill;
import eu.openmos.model.SubSystem;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SystemConfigurator", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SystemConfigurator {


    /**
     * 
     * @param recipe
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "createNewRecipe", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewRecipe")
    @ResponseWrapper(localName = "createNewRecipeResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewRecipeResponse")
    public ServiceCallStatus createNewRecipe(
        @WebParam(name = "recipe", targetNamespace = "")
        Recipe recipe);

    /**
     * 
     * @param operationTimestamp
     * @param orderId
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "orderRemoval", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.OrderRemoval")
    @ResponseWrapper(localName = "orderRemovalResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.OrderRemovalResponse")
    public ServiceCallStatus orderRemoval(
        @WebParam(name = "orderId", targetNamespace = "")
        String orderId,
        @WebParam(name = "operationTimestamp", targetNamespace = "")
        String operationTimestamp);

    /**
     * 
     * @param cyberPhysicalAgentDescription
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "createNewResourceAgent", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewResourceAgent")
    @ResponseWrapper(localName = "createNewResourceAgentResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewResourceAgentResponse")
    public ServiceCallStatus createNewResourceAgent(
        @WebParam(name = "cyberPhysicalAgentDescription", targetNamespace = "")
        SubSystem cyberPhysicalAgentDescription);

    /**
     * 
     * @param order
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "orderUpdate", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.OrderUpdate")
    @ResponseWrapper(localName = "orderUpdateResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.OrderUpdateResponse")
    public ServiceCallStatus orderUpdate(
        @WebParam(name = "order", targetNamespace = "")
        Order order);

    /**
     * 
     * @param newOrder
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "acceptNewOrder", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.AcceptNewOrder")
    @ResponseWrapper(localName = "acceptNewOrderResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.AcceptNewOrderResponse")
    public ServiceCallStatus acceptNewOrder(
        @WebParam(name = "newOrder", targetNamespace = "")
        Order newOrder);

    /**
     * 
     * @param cyberPhysicalAgentDescription
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "createNewTransportAgent", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewTransportAgent")
    @ResponseWrapper(localName = "createNewTransportAgentResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewTransportAgentResponse")
    public ServiceCallStatus createNewTransportAgent(
        @WebParam(name = "cyberPhysicalAgentDescription", targetNamespace = "")
        SubSystem cyberPhysicalAgentDescription);

    /**
     * 
     * @param operationTimestamp
     * @param productId
     * @param equipmentId
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "finishedProduct", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.FinishedProduct")
    @ResponseWrapper(localName = "finishedProductResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.FinishedProductResponse")
    public ServiceCallStatus finishedProduct(
        @WebParam(name = "equipmentId", targetNamespace = "")
        String equipmentId,
        @WebParam(name = "productId", targetNamespace = "")
        String productId,
        @WebParam(name = "operationTimestamp", targetNamespace = "")
        String operationTimestamp);

    /**
     * 
     * @param orders
     * @param cyberPhysicalAgentDescriptions
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "initializePlatform", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.InitializePlatform")
    @ResponseWrapper(localName = "initializePlatformResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.InitializePlatformResponse")
    public ServiceCallStatus initializePlatform(
        @WebParam(name = "cyberPhysicalAgentDescriptions", targetNamespace = "")
        List<SubSystem> cyberPhysicalAgentDescriptions,
        @WebParam(name = "orders", targetNamespace = "")
        List<Order> orders);

    /**
     * 
     * @param skill
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "createNewSkill", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewSkill")
    @ResponseWrapper(localName = "createNewSkillResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.CreateNewSkillResponse")
    public ServiceCallStatus createNewSkill(
        @WebParam(name = "skill", targetNamespace = "")
        Skill skill);

    /**
     * 
     * @param agentUniqueName
     * @return
     *     returns eu.openmos.agentcloud.utilities.ServiceCallStatus
     */
    @WebMethod
    @WebResult(name = "serviceCallStatus", targetNamespace = "")
    @RequestWrapper(localName = "removeAgent", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.RemoveAgent")
    @ResponseWrapper(localName = "removeAgentResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.systemconfigurator.wsimport.RemoveAgentResponse")
    public ServiceCallStatus removeAgent(
        @WebParam(name = "agentUniqueName", targetNamespace = "")
        String agentUniqueName);

}
