
package eu.openmos.agentcloud.ws.productionoptimizer.wsimport;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductionOptimizer", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", wsdlLocation = "/wsdl/wsProductionOptimizer.wsdl")
public class ProductionOptimizer_Service
    extends Service
{

    private final static URL PRODUCTIONOPTIMIZER_WSDL_LOCATION;
    private final static WebServiceException PRODUCTIONOPTIMIZER_EXCEPTION;
    private final static QName PRODUCTIONOPTIMIZER_QNAME = new QName("http://productionoptimizer.optimizer.agentcloud.openmos.eu/", "ProductionOptimizer");

    static {
        PRODUCTIONOPTIMIZER_WSDL_LOCATION = eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ProductionOptimizer_Service.class.getResource("/wsdl/wsProductionOptimizer.wsdl");
        WebServiceException e = null;
        if (PRODUCTIONOPTIMIZER_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/wsProductionOptimizer.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PRODUCTIONOPTIMIZER_EXCEPTION = e;
    }

    public ProductionOptimizer_Service() {
        super(__getWsdlLocation(), PRODUCTIONOPTIMIZER_QNAME);
    }

    public ProductionOptimizer_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTIONOPTIMIZER_QNAME, features);
    }

    public ProductionOptimizer_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTIONOPTIMIZER_QNAME);
    }

    public ProductionOptimizer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTIONOPTIMIZER_QNAME, features);
    }

    public ProductionOptimizer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductionOptimizer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductionOptimizer
     */
    @WebEndpoint(name = "ProductionOptimizerImplPort")
    public ProductionOptimizer getProductionOptimizerImplPort() {
        return super.getPort(new QName("http://productionoptimizer.optimizer.agentcloud.openmos.eu/", "ProductionOptimizerImplPort"), ProductionOptimizer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductionOptimizer
     */
    @WebEndpoint(name = "ProductionOptimizerImplPort")
    public ProductionOptimizer getProductionOptimizerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://productionoptimizer.optimizer.agentcloud.openmos.eu/", "ProductionOptimizerImplPort"), ProductionOptimizer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTIONOPTIMIZER_EXCEPTION!= null) {
            throw PRODUCTIONOPTIMIZER_EXCEPTION;
        }
        return PRODUCTIONOPTIMIZER_WSDL_LOCATION;
    }

}
