
package eu.openmos.agentcloud.ws.productionoptimizer.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import eu.openmos.agentcloud.data.recipe.Recipe;
import eu.openmos.agentcloud.optimizer.data.OptimizationParameter;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductionOptimizer", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductionOptimizer {


    /**
     * 
     * @return
     *     returns eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ProductionOptimizerResponseBean
     */
    @WebMethod
    @WebResult(name = "productionOptimizerResponseBean", targetNamespace = "")
    @RequestWrapper(localName = "resetOptimizer", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ResetOptimizer")
    @ResponseWrapper(localName = "resetOptimizerResponse", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ResetOptimizerResponse")
    public ProductionOptimizerResponseBean resetOptimizer();

    /**
     * 
     * @return
     *     returns java.util.List<eu.openmos.agentcloud.data.recipe.Recipe>
     */
    @WebMethod
    @WebResult(name = "optimizedRecipes", targetNamespace = "")
    @RequestWrapper(localName = "optimize", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.Optimize")
    @ResponseWrapper(localName = "optimizeResponse", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.OptimizeResponse")
    public List<Recipe> optimize();

    /**
     * 
     * @return
     *     returns eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ProductionOptimizerResponseBean
     */
    @WebMethod
    @WebResult(name = "productionOptimizerResponseBean", targetNamespace = "")
    @RequestWrapper(localName = "stopOptimizer", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.StopOptimizer")
    @ResponseWrapper(localName = "stopOptimizerResponse", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.StopOptimizerResponse")
    public ProductionOptimizerResponseBean stopOptimizer();

    /**
     * 
     * @param newParameters
     * @return
     *     returns eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ProductionOptimizerResponseBean
     */
    @WebMethod
    @WebResult(name = "productionOptimizerResponseBean", targetNamespace = "")
    @RequestWrapper(localName = "reparametrizeOptimizer", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ReparametrizeOptimizer")
    @ResponseWrapper(localName = "reparametrizeOptimizerResponse", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ReparametrizeOptimizerResponse")
    public ProductionOptimizerResponseBean reparametrizeOptimizer(
        @WebParam(name = "newParameters", targetNamespace = "")
        List<OptimizationParameter> newParameters);

    /**
     * 
     * @return
     *     returns eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ProductionOptimizerResponseBean
     */
    @WebMethod
    @WebResult(name = "productionOptimizerResponseBean", targetNamespace = "")
    @RequestWrapper(localName = "initializeOptimizer", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.InitializeOptimizer")
    @ResponseWrapper(localName = "initializeOptimizerResponse", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.InitializeOptimizerResponse")
    public ProductionOptimizerResponseBean initializeOptimizer();

    /**
     * 
     * @return
     *     returns eu.openmos.agentcloud.ws.productionoptimizer.wsimport.ProductionOptimizerResponseBean
     */
    @WebMethod
    @WebResult(name = "productionOptimizerResponseBean", targetNamespace = "")
    @RequestWrapper(localName = "isOptimizable", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.IsOptimizable")
    @ResponseWrapper(localName = "isOptimizableResponse", targetNamespace = "http://productionoptimizer.optimizer.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.productionoptimizer.wsimport.IsOptimizableResponse")
    public ProductionOptimizerResponseBean isOptimizable();

}
